name: probatorio-sup
channels:
  - conda-forge
dependencies:
  # Should be on every project
  - python==3.13.*
  # For building latex documents
  - make
  - tectonic
  # Project specific dependencies

